// One-time local dev setup: writes a working .env with an absolute
// DATABASE_URL (see the README for why it must be absolute) and freshly
// generated secrets, so a fresh clone can go straight from `npm install`
// to `npm run dev` with no manual editing.
//
// Safe to re-run: if .env already exists, it's left untouched.

import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import path from "node:path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const envPath = path.join(projectRoot, ".env");

if (existsSync(envPath)) {
  console.log("→ .env already exists — leaving it as is.");
  console.log("  (delete it first if you want setup to regenerate it)");
  process.exit(0);
}

const dbPath = path.join(projectRoot, "prisma", "dev.db");
const sessionSecret = randomBytes(32).toString("hex");
const adminPassword = randomBytes(9).toString("base64url");

const contents = `DATABASE_URL="file:${dbPath}"

# Auto-generated by \`npm run setup\`. This is your dashboard password —
# printing.ar9.top/dashboard/login (or http://localhost:3000/dashboard/login
# locally) — change it any time by editing this line.
ADMIN_PASSWORD="${adminPassword}"

SESSION_SECRET="${sessionSecret}"
`;

writeFileSync(envPath, contents);

console.log("✓ Created .env for local development.\n");
console.log(`  Dashboard password: ${adminPassword}`);
console.log("  (also saved in .env — change ADMIN_PASSWORD there any time)\n");
console.log("Next steps:");
console.log("  npx prisma migrate deploy");
console.log("  npm run dev");
